### ISSUE TITLE
A typo in the file data_stat_cpu.py

### ISSUE THREAD

**Issue by wenh06** [TimingPredict/TimingPredict#1]
Line 30

```python
data_test_ensemble = ensemble(data_train)
```

should be

```python
data_test_ensemble = ensemble(data_test)
```

However, the variable `data_test_ensemble` is not used elsewhere (imported in `train_stat_rf.py` but not used).

**Comment by gzz2000** [comment]
Thanks for pointing this out! It is two old lines of code not used in the current version. I deleted them just now.
