### ISSUE TITLE
the meaning of groundtruth

### ISSUE THREAD

**Issue by Pxx-X** [TimingPredict/TimingPredict#11]
can you please tell me what is the meaning of "groundtruth" in the code? I don't get it, thank you

**Comment by gzz2000** [comment]
Sorry for the late response, but they are a trick in training. They cut off the error propagation during unstable stages. On testing they are not adopted.

**Comment by PxmmmmGH** [comment]
So should I apply "groundtruth = True" when training the model, and apply "groundtruth=false" when test the model? and It is what "asynchronously" means in paper? 

another related question confuse me: I found that groundtruth value is used at primary input level when testing the model, is it a compromise for asynchronous update scheme? And is it a wrong way to use groundtruth value during testing the model, which make the model impractical

**Comment by gzz2000** [comment]
> So should I apply "groundtruth = True" when training the model, and apply "groundtruth=false" when test the model? and It is what "asynchronously" means in paper?

Yes. you are right!


> another related question confuse me: I found that groundtruth value is used at primary input level when testing the model, is it a compromise for asynchronous update scheme? And is it a wrong way to use groundtruth value during testing the model, which make the model impractical

It is not a compromise, because STA knows the arrival time of primary inputs in advance. They are usually specified in a file called Synopsys Design Constraints (SDC) with set_input_delay command.
