### ISSUE TITLE
How to deal with labels and features that do not correspond

### ISSUE THREAD

**Issue by SaltyfishK423** [TimingPredict/TimingPredict#12]
Hello, I was referring to your work to generate new data, and I found that some features and labels could not correspond to each other after using EDA tools to perform CTS because of buffer insertions. May I ask how do you deal with it?

**Comment by gzz2000** [comment]
This is a very good research topic. I've heard many different ways to deal with this.
One simple way is to only pay attention to pins that corresponds between stages, and ignore the newly-generated pins. These new pins do not propagate loss and their features can be (in some way or other) distributed to surrounding valid pins.
Another more sophisticated way is to instead look for **invariant features** across these netlist-changing stages. One example: you can use timing endpoints (primary outputs, flip-flops, etc), as they do not change with CTS and they provide sufficient information for slack calculation.

**Comment by SaltyfishK423** [comment]
Thanks for your reply, I got some inspiration
