### ISSUE TITLE
Graph containing a loop

### ISSUE THREAD

**Issue by junseokhur** [TimingPredict/TimingPredict#14]
Hi, I have one more question

How do I create a topology in data_graph.py if graph has a loop?

Error occurs at "topo = dgl.topological_nodes_generator(g)" in data_graph.py
because of the loops.

Some netlists have loops and I'm curious how this problem was solved.

**Comment by gzz2000** [comment]
Normally there should not be a loop. If there is, it should be investigated and broken before we do timing analysis
