### ISSUE TITLE
Understanding the Role of the Third Convolutional Layer in Net Embedding Model

### ISSUE THREAD

**Issue by SaltyfishK423** [TimingPredict/TimingPredict#15]
Hello, I have run your code and find that although there are three convolution layers in the Net Embedding model, the node can only receive the information on the corresponding net edge, which means each node can only accept one-hop information. Two convolution layers have been able to implement graph broadcast and graph reduction updates, I would like to ask what is the function of the third convolution layer.

**Comment by gzz2000** [comment]
In principle two layers of MLP is able to fit arbitrary function, but deeper models are shown easier to be trained to perform well. Each of our 3 layers actually has both broadcast and reduction. So our model looks like: broadcast - reduce - broadcast - reduce - broadcast - reduce.
