### ISSUE TITLE
Judging pi_nodes/po_nodes in data_graph.py

### ISSUE THREAD

**Issue by zerzerzerz** [TimingPredict/TimingPredict#2]
- In line 54, `g.ndata['nf'][:, 1] < 0.5` shows it is an input_node
- In line 57, `'pi_nodes': torch.logical_and(g.ndata['nf'][:, 1] > 0.5, g.ndata['nf'][:, 0] > 0.5).` shows it is an primary input node
- But in line 54, `g.ndata['nf'][:, 1] < 0.5` and in line 57, `g.ndata['nf'][:, 1] > 0.5`
- I want to know whether it is correct which means I misunderstand something or this is a typo?
- Thanks!

**Comment by gzz2000** [comment]
This is a good question and this is not a typo. In fact, primary inputs are actually “outputs” because they act like gate outputs in a timing analysis scenario. They drive nets instead of being driven by nets like gate inputs. Similarly, primary outputs are actually “inputs”.

**Comment by zerzerzerz** [comment]
- Thank you very much!
