### ISSUE TITLE
How to compute slack?

### ISSUE THREAD

**Issue by zerzerzerz** [TimingPredict/TimingPredict#3]
Hello. I want to compute slack with AT and RAT, but it seems that the model only predicts AT. So how to compute the slack for each timing endpoint? Thank you!

**Comment by gzz2000** [comment]
Hello, the required arrival time is usually supplied externally in SDC files, like this:
https://github.com/OpenTimer/OpenTimer/blob/master/example/simple/simple.sdc#L27

So you just need to compute the difference between the AT at endpoints and the corresponding constraints.

**Comment by zerzerzerz** [comment]
> Hello, the required arrival time is usually supplied externally in SDC files, like this: https://github.com/OpenTimer/OpenTimer/blob/master/example/simple/simple.sdc#L27
> 
> So you just need to compute the difference between the AT at endpoints and the corresponding constraints.

Thanks and I will try it
